name: build
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetupNodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
        
      
      - name: build-step-1
        run:
          npm install
      - name: Check-Dir
        run: dir

      - name: build-step-2
        run:
          npm run tauri dev
      - name: build-step-3
        run:
          tar vcf debug.tar ./src-tauri/debug/webview.exe
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Webview
          path: ./debug.tar