name: build
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetupNodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
        
      
      - name: build-step-1
        run:
            npm config set registry https://registry.npmjs.org
      - name: build-step-2
        run: 
          npm install
      - name: build-step-3
        run:
          npm run tauri build
      - name: Upload
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          copy .\src-tauri\target\release\webview.exe .\webview.exe
          rd /s /q .\src-tauri\
          rd /s /q .\node_modules\
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add .
          git commit -m "1"
          git push git@github.com:wuliaodexiaoluo/build.git